$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
$OutputEncoding = [System.Text.UTF8Encoding]::new()

$meta = @{}
if (Test-Path "topics_meta.txt") {
  Get-Content "topics_meta.txt" -Encoding UTF8 | ForEach-Object {
    if ($_ -match "^([^|]+)\|([^|]+)\|([^|]+)\|(.*)$") {
      $meta[$matches[1]] = @{ title=$matches[2]; desc=$matches[3]; anim=$matches[4] }
    }
  }
}

function Get-RelPath([string]$fullPath) {
  $base = (Get-Location).Path
  $rel = $fullPath.Substring($base.Length + 1)
  return ($rel -replace "\\", "/")
}

$dirs = @(Get-ChildItem -Path "output" -Directory -Filter "*_steps" | Sort-Object Name)
$sections = ""
$plainSections = ""

foreach ($d in $dirs) {
  $key = $d.Name -replace "_steps$", ""
  if ($meta.ContainsKey($key)) {
    $title = $meta[$key].title
    $desc  = $meta[$key].desc
    $anim  = $meta[$key].anim
  } else {
    $title = $key
    $desc  = "This topic is generated by C++ as step-by-step SVG frames."
    $anim  = "The animation shows the algorithm or concept one frame at a time."
  }

  $frames = @(Get-ChildItem $d.FullName -Filter "step_*.svg" | Sort-Object Name)
  if ($frames.Count -eq 0) { continue }

  $frameList = @()
  foreach ($f in $frames) { $frameList += ('"' + (Get-RelPath $f.FullName) + '"') }
  $arr = $frameList -join ","
  $first = Get-RelPath $frames[0].FullName

  $imgs = ""
  foreach ($f in $frames) {
    $src = Get-RelPath $f.FullName
    $imgs += "<img class='plain-img' src='$src'>`n"
  }

  $sections += @"
<details class="card">
  <summary>$title</summary>
  <div class="desc">
    <h3>主題說明</h3>
    <p>$desc</p>
    <h3>動畫說明</h3>
    <p>$anim</p>
  </div>
  <div class="controls">
    <button onclick="prevFrame('$key')">上一張</button>
    <button onclick="nextFrame('$key')">下一張</button>
    <button onclick="togglePlay('$key')">自動播放 / 暫停</button>
    <label>播放速度
      <select id="speed_$key" onchange="restartTimer('$key')">
        <option value="1500">慢 1.5s</option>
        <option value="1000" selected>正常 1s</option>
        <option value="500">快 0.5s</option>
      </select>
    </label>
    <span id="counter_$key"></span>
  </div>
  <img id="img_$key" class="stage" src="$first" alt="$title step animation">
  <script>frames['$key']=[$arr]; indexMap['$key']=0;</script>
</details>
"@

  $plainSections += @"
<details class="card">
  <summary>$title</summary>
  <div class="desc">
    <h3>主題說明</h3>
    <p>$desc</p>
    <h3>動畫說明</h3>
    <p>$anim</p>
  </div>
  <div class="grid">
$imgs
  </div>
</details>
"@
}

$style = @"
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body{font-family:'Microsoft JhengHei',Arial,sans-serif;background:#eef2f7;margin:0;color:#18202f}
header{background:#1f3763;color:white;padding:24px 36px}
main{max-width:1180px;margin:24px auto;padding:0 16px}
.card{background:white;margin:16px 0;border-radius:14px;box-shadow:0 4px 14px #0002;overflow:hidden}
.card summary{cursor:pointer;font-size:22px;font-weight:700;padding:18px 24px;background:#dfe8f7}
.desc{padding:18px 24px;line-height:1.8}
.controls{padding:12px 24px;background:#f7f9fc;display:flex;gap:12px;align-items:center;flex-wrap:wrap}
.controls button{padding:8px 14px;border:0;border-radius:8px;background:#1f3763;color:white;cursor:pointer}
.controls select{padding:6px;border-radius:6px}
.stage{display:block;max-width:100%;margin:18px auto;border:1px solid #ccd;border-radius:10px;background:white}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:16px;padding:18px}
.plain-img{width:100%;border:1px solid #ccd;border-radius:10px;background:white}
</style>
"@

$js = @"
<script>
function show(k){
  const img=document.getElementById('img_'+k);
  const c=document.getElementById('counter_'+k);
  if(!img || !frames[k] || frames[k].length===0) return;
  img.src=frames[k][indexMap[k]];
  if(c) c.textContent=(indexMap[k]+1)+' / '+frames[k].length;
}
function nextFrame(k){ indexMap[k]=(indexMap[k]+1)%frames[k].length; show(k); }
function prevFrame(k){ indexMap[k]=(indexMap[k]-1+frames[k].length)%frames[k].length; show(k); }
function getSpeed(k){ const s=document.getElementById('speed_'+k); return parseInt((s&&s.value)||1000); }
function togglePlay(k){
  if(timers[k]){ clearInterval(timers[k]); timers[k]=null; return; }
  timers[k]=setInterval(()=>nextFrame(k), getSpeed(k));
}
function restartTimer(k){
  if(timers[k]){ clearInterval(timers[k]); timers[k]=setInterval(()=>nextFrame(k), getSpeed(k)); }
}
window.addEventListener('load',()=>Object.keys(frames).forEach(show));
</script>
"@

$html = @"
<!doctype html>
<html>
<head>
$style
<title>lec6a Step-by-step SVG Animation</title>
</head>
<body>
<header>
  <h1>lec6a Graphs Part I：C++ SVG 動畫教學</h1>
  <p>C++ 產生 step-by-step SVG，PowerShell 自動產生 HTML。每個下拉式主題包含主題說明、動畫說明、播放速度與自動播放。</p>
</header>
<main>
<script>var frames={}, indexMap={}, timers={};</script>
$sections
</main>
$js
</body>
</html>
"@
Set-Content -Path "index.html" -Value $html -Encoding UTF8

$plain = @"
<!doctype html>
<html>
<head>
$style
<title>lec6a All SVG Frames</title>
</head>
<body>
<header>
  <h1>lec6a 全部 SVG 連環圖</h1>
  <p>本頁由 PowerShell 自動產生，直接展開所有 C++ 產生的 SVG frames。</p>
</header>
<main>
$plainSections
</main>
</body>
</html>
"@
Set-Content -Path "auto_generated_index.html" -Value $plain -Encoding UTF8
Write-Host "Generated index.html and auto_generated_index.html"
