#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"節點分成 data 與 link","Chain 物件 has-a first pointer","說明封裝與節點關係"};
    string s=startSVG(1280,720,"Node Class and Has-a Relation","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Node object contains data field and link field; Chain has-a first pointer.","sub");
    s+=R(80,180,220,170,"box",""); s+=T(110,215,"class Chain","title"); s+=T(110,255,"private: ChainNode<T>* first","small"); s+=T(110,285,"public operations use first","small");
    s+=R(420,170,230,190,"note",""); s+=T(455,210,"class ChainNode","title"); s+=R(455,240,78,52,"data","data"); s+=R(540,240,78,52,"link","link"); if(step>=3) s+=L(300,260,420,260,"redptr");
    s+=listNode(780,210,"10",step>=5); s+=listNode(940,210,"20",step>=6); s+=L(896,236,940,236,step>=6?"redptr":"ptr");
    s+=T(80,430,"重點：使用者操作 Chain ADT，不直接依賴節點內部配置，這就是封裝。","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 03_node_class_and_has_a.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/03_node_class_and_has_a_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
