#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"先保存 next","把新節點指向後方","再讓前節點指向新節點"};
    string s=startSVG(1280,720,"Pointer Manipulation","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Insert new node after p: new->link = p->link, then p->link = new.","sub");
    s+=T(90,185,"p","sub"); s+=listNode(130,210,"A",step>=2); s+=listNode(430,210,"B",step>=3); s+=L(246,236,430,236, step<6?"ptr":"redptr");
    s+=listNode(280,360,"X",step>=4); s+=T(280,340,"new node","small");
    if(step>=4) s+=L(396,386,430,260,"redptr");
    if(step>=6) s+=L(246,236,280,360,"redptr");
    s+=T(70,520,"順序不可顛倒：若先 p->link = new，原本 B 的位址會遺失，造成串列斷掉。","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 04_pointer_manipulation.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/04_pointer_manipulation_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
