#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"泛型 T 存放資料","iterator 指向目前節點","++ 代表沿 link 移動"};
    string s=startSVG(1280,720,"Template Chain Iterator","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Template Chain<T> can store different data types; iterator hides pointer walking.","sub");
    s+=T(90,190,"Chain<string>","sub"); vector<string>v={"cat","dog","fox"}; for(int i=0;i<3;i++){s+=listNode(100+i*170,220,v[i],step==i+2); if(i<2)s+=L(216+i*170,246,270+i*170,246,"ptr");}
    int pos=min(max(step-2,0),2); s+=T(100+pos*170,310,"iterator current","small"); s+=L(160+pos*170,300,160+pos*170,270,"redptr");
    s+=R(100,430,520,90,"note",""); s+=T(130,465,"operator++ moves current = current->link","sub"); s+=T(130,495,"operator* returns current->data","sub");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 06_template_chain_iterator.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/06_template_chain_iterator_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
