#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"last 指向尾節點","last->link 回到第一個節點","用 last 可快速找到頭尾"};
    string s=startSVG(1280,720,"Circular List Last Pointer","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Circular list: last->link points to the first node instead of NULL.","sub");
    s+=listNode(150,240,"A",step==2); s+=listNode(350,240,"B",step==3); s+=listNode(550,240,"C",step==4); s+=L(266,266,350,266,"ptr"); s+=L(466,266,550,266,"ptr");
    s+=T(610,210,"last","sub"); s+=L(650,220,630,240,"redptr"); if(step>=5) s+=L(666,266,150,266,"redptr");
    s+=T(120,430,"使用 last 可以 O(1) 找到第一個節點：first = last->link，也可快速尾端插入。","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 08_circular_list_last_pointer.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/08_circular_list_last_pointer_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
