#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"讀入 row col value","建立 row/col header","destructor 逐列釋放節點"};
    string s=startSVG(1280,720,"Sparse Matrix Input and Destructor","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Sparse matrix input builds nodes; destructor releases row chains safely.","sub");
    s+=R(100,190,260,110,"note",""); s+=T(125,225,"Input triples: row col value","sub"); s+=T(125,255,"(0,2,8), (2,1,6), (3,3,9)","small");
    if(step>=2){s+=R(430,200,90,50,"hot","0,2,8"); s+=R(560,260,90,50,"hot","2,1,6"); s+=R(690,320,90,50,"hot","3,3,9");}
    if(step>=5){s+=T(100,430,"Destructor: visit each row header, delete every node in that row, then delete headers.","sub"); s+=L(430,450,560,450,"redptr"); s+=L(560,450,690,450,"redptr");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 15_sparse_matrix_input_destructor.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/15_sparse_matrix_input_destructor_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
