#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"建立 first 指標","逐節點沿 link 前進","最後遇到 NULL 停止"};
    string s=startSVG(1280,720,"Singly Linked Chain","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Singly linked list traversal: first -> node -> node -> NULL","sub");
    s+=T(70,188,"first","sub"); s+=L(120,183,165,213, step>=1?"redptr":"ptr");
    vector<string>v={"A","B","C","D"}; for(int i=0;i<4;i++){s+=listNode(170+i*155,195,v[i],step==i+2); if(i<3) s+=L(286+i*155,221,325+i*155,221, step==i+3?"redptr":"ptr");}
    s+=T(790,560,"NULL","sub"); s+=L(751,221,790,550, step>=7?"redptr":"ptr");
    s+=T(80,330,"每一步只知道目前節點與下一個 link，不能 O(1) 直接跳到任意位置。","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 02_singly_linked_chain.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/02_singly_linked_chain_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
