#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"從空串列建立","插入新節點","刪除時先接線再釋放"};
    string s=startSVG(1280,720,"Create Insert Delete Chain","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Create, insert, delete: list changes by allocating nodes and reconnecting links.","sub");
    int n=min(step,4); vector<string>v={"A","B","C","D"}; for(int i=0;i<n;i++){s+=listNode(100+i*150,220,v[i],i==n-1); if(i<n-1)s+=L(216+i*150,246,250+i*150,246,"ptr");}
    if(step>=5){s+=T(100,360,"Insert X between B and C","sub"); s+=listNode(330,400,"X",true); s+=L(366,246,330,400,"redptr"); s+=L(446,426,400,246,"redptr");}
    if(step>=7){s+=T(100,560,"Delete B: previous node bypasses B, then B can be returned to memory.","small"); s+=L(216,246,400,246,"redptr");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 05_create_insert_delete_chain.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/05_create_insert_delete_chain_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
