#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"Stack 在 top push/pop","Queue 在 rear 插入、front 刪除","比較 LIFO 與 FIFO"};
    string s=startSVG(1280,720,"Linked Stack and Queue","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Linked stack uses top; linked queue uses front and rear.","sub");
    s+=T(100,190,"Stack push/pop at top (LIFO)","sub"); for(int i=0;i<3;i++){s+=listNode(120,230+i*65,string(1,'A'+i),step==i+2); if(i<2)s+=L(178,282+i*65,178,295+i*65,"ptr");} s+=T(70,250,"top","small"); s+=L(105,245,120,245,"redptr");
    s+=T(430,190,"Queue enqueue at rear, dequeue at front (FIFO)","sub"); for(int i=0;i<3;i++){s+=listNode(450+i*150,250,string(1,'X'+i),step>=5+i); if(i<2)s+=L(566+i*150,276,600+i*150,276,"ptr");} s+=T(440,330,"front","small"); s+=T(740,330,"rear","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 10_linked_stack_queue.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/10_linked_stack_queue_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
