#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"非零元素用節點表示","row link 串同列","col link 串同欄"};
    string s=startSVG(1280,720,"Sparse Matrix Orthogonal List","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Orthogonal list stores sparse matrix nonzero entries with row and column links.","sub");
    for(int r=0;r<4;r++) for(int c=0;c<4;c++) s+=R(100+c*55,190+r*45,50,40,(r==1&&c==2)||(r==3&&c==0)?"hot":"box", ((r==1&&c==2)?"7":((r==3&&c==0)?"5":"")) );
    s+=T(390,190,"row headers","sub"); for(int r=0;r<4;r++){s+=R(400,210+r*60,80,42,"note","row"+to_string(r));}
    s+=T(580,190,"nonzero nodes","sub"); s+=R(590,245,90,52,"hot","(1,2,7)"); s+=R(590,360,90,52,"hot","(3,0,5)"); if(step>=4){s+=L(480,291,590,271,"redptr"); s+=L(480,399,590,386,"redptr");}
    if(step>=6){s+=T(720,270,"column links connect entries in same column","small"); s+=L(635,360,635,297,"redptr");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 14_sparse_matrix_orthogonal_list.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/14_sparse_matrix_orthogonal_list_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
