#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"每節點有 left/right link","可雙向走訪","插入刪除需更新四條 link"};
    string s=startSVG(1280,720,"Doubly Linked List","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Doubly linked list supports forward and backward traversal.","sub");
    for(int i=0;i<3;i++){s+=dllNode(120+i*200,230,string(1,'A'+i),step==i+2); if(i<2){s+=L(266+i*200,256,320+i*200,256,"ptr"); s+=L(320+i*200,286,266+i*200,286,"dash");}}
    if(step>=5){s+=T(130,410,"Insert X between A and B: update X.left, X.right, A.right, B.left","sub"); s+=dllNode(270,470,"X",true); s+=L(266,256,270,470,"redptr"); s+=L(416,496,320,286,"redptr");}
    if(step>=7){s+=T(130,640,"Delete node: predecessor and successor must both bypass the removed node.","small");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 16_doubly_linked_list.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/16_doubly_linked_list_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
