#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"比較連續記憶體與鏈結記憶體","示範插入造成搬移或改 pointer","理解 O(n) 與 O(1) 差異"};
    string s=startSVG(1280,720,"Sequential vs. Linked Representation","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Sequential array: insert in middle must shift following elements","sub");
    vector<string>a={"EAT","FAT", step>=3?"GAT":"", "HAT",""}; for(int i=0;i<5;i++) s+=cell(80+i*78,170,a[i], step==i+1 || (step>=3&&i==2));
    if(step>=2) s+=L(248,245,248,205,"redptr"), s+=T(210,270,"shift HAT right before inserting GAT","small");
    s+=T(60,370,"Linked chain: insert by rewiring link fields","sub");
    s+=listNode(80,410,"EAT",step==5); s+=listNode(260,410,"FAT",step==6); s+=listNode(440,410,"HAT",step==7); if(step<6){s+=L(196,436,260,436);} else {s+=L(196,436,260,436,"redptr");} if(step<7){s+=L(376,436,440,436);} else {s+=L(376,436,440,436,"redptr");}
    if(step>=6){s+=listNode(260,520,"GAT",true); s+=L(376,436,300,520,"redptr"); s+=L(376,546,440,436,"redptr");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 01_sequential_vs_linked.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/01_sequential_vs_linked_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
