#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"尾端插入維持 last","串接兩條 chain","反轉每個 link 方向"};
    string s=startSVG(1280,720,"InsertBack Concatenate Reverse","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"InsertBack, concatenate and reverse are common chain operations.","sub");
    vector<string>v={"A","B","C"}; for(int i=0;i<3;i++){s+=listNode(100+i*160,200,v[i],step==i+1); if(i<2)s+=L(216+i*160,226,260+i*160,226,"ptr");}
    if(step>=3){s+=T(520,226,"last","sub"); s+=L(560,220,540,220,"redptr");}
    if(step>=4){s+=T(100,340,"Concatenate second chain","sub"); s+=listNode(500,360,"D",true); s+=listNode(660,360,"E",true); s+=L(616,386,660,386,"ptr"); s+=L(536,226,500,360,"redptr");}
    if(step>=6){s+=T(100,560,"Reverse: repeatedly redirect each node link to previous node.","small"); s+=L(420,226,260,226,"redptr"); s+=L(260,226,100,226,"redptr");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 07_insertback_concatenate_reverse.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/07_insertback_concatenate_reverse_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
