#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"比較兩多項式指標","相同 exponent 相加","不同 exponent 複製較大項"};
    string s=startSVG(1280,720,"Polynomial Addition","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Polynomial addition walks two ordered chains and compares exponents.","sub");
    s+=T(90,190,"A(x)","sub"); s+=R(140,210,70,48,"data","3"); s+=R(210,210,70,48,"box","5"); s+=R(320,210,70,48,"data","2"); s+=R(390,210,70,48,"box","2"); s+=L(280,234,320,234,"ptr");
    s+=T(90,300,"B(x)","sub"); s+=R(140,320,70,48,"data","4"); s+=R(210,320,70,48,"box","5"); s+=R(320,320,70,48,"data","1"); s+=R(390,320,70,48,"box","1"); s+=L(280,344,320,344,"ptr");
    if(step>=3){s+=T(520,250,"Same exponent 5: 3 + 4 = 7","sub"); s+=R(620,300,70,48,"hot","7"); s+=R(690,300,70,48,"hot","5");}
    if(step>=5){s+=T(520,390,"Then copy larger/smaller remaining exponent terms.","small"); s+=R(780,300,70,48,"data","2"); s+=R(850,300,70,48,"box","2");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 13_polynomial_addition.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/13_polynomial_addition_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
