#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"header 當固定入口","空表 header 指回自己","插入刪除不必處理特殊頭節點"};
    string s=startSVG(1280,720,"Circular List with Header Node","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Header node gives a fixed entry point; even an empty circular list has a header.","sub");
    s+=listNode(120,240,"HEAD",step==1); if(step==1) s+=L(236,266,120,266,"redptr");
    if(step>=2){s+=listNode(330,240,"A",step==2); s+=L(236,266,330,266,"redptr"); s+=L(446,266,120,266,"ptr");}
    if(step>=4){s+=listNode(540,240,"B",step==4); s+=L(446,266,540,266,"redptr"); s+=L(656,266,120,266,"ptr");}
    s+=T(100,430,"Header 不存真正資料，主要讓插入第一個節點與刪除第一個節點的程式邏輯一致。","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 09_circular_header_node.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/09_circular_header_node_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
