#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"刪除節點進入 av list","new node 可從 av list 取回","降低反覆配置成本"};
    string s=startSVG(1280,720,"Available Space List","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Available space list collects deleted nodes for later reuse.","sub");
    s+=T(100,190,"Active chain","sub"); s+=listNode(120,220,"A",false); s+=listNode(300,220,"B",step>=2); s+=listNode(480,220,"C",false); s+=L(236,246,300,246,"ptr"); s+=L(416,246,480,246,"ptr");
    if(step>=4){s+=T(100,380,"After deleting B, B goes to av list","sub"); s+=listNode(300,420,"B",true); s+=T(250,450,"av","sub"); s+=L(280,445,300,445,"redptr"); s+=L(236,246,480,246,"redptr");}
    if(step>=7){s+=T(540,450,"new node can reuse B's storage","small"); s+=L(416,446,560,446,"redptr");}

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 11_available_space_list.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/11_available_space_list_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
