#include "svg_helper.h"

string drawFrame(int step){
    vector<string> focus = {"每節點存 coef 與 exp","依 exponent 排列","表示稀疏多項式"};
    string s=startSVG(1280,720,"Polynomial Chain","Step "+to_string(step)+" / 8 - "+"由 C++ 程式輸出 step-by-step SVG 動畫");
    s += sidePanel(step, focus);

    s+=T(60,135,"Polynomial chain stores only nonzero terms: coefficient and exponent.","sub");
    vector<pair<string,string>> v={{"3","14"},{"2","8"},{"1","0"}}; for(int i=0;i<3;i++){ int x=110+i*210; s+=R(x,230,70,54,step==i+2?"hot":"data",v[i].first); s+=R(x+70,230,70,54,"box",v[i].second); s+=R(x+140,230,40,54,"link","*"); if(i<2)s+=L(x+180,257,x+210,257,"ptr"); }
    s+=T(110,320,"Represents: 3x^14 + 2x^8 + 1","sub"); s+=T(110,360,"每個節點 = coef, exp, link；不需要存 0 係數項。","small");

    s+=R(80,640,820,42,"ok",""); s+=T(105,667,"This SVG frame is generated by C++ program: 12_polynomial_chain.cpp. HTML only loads generated step_XX.svg files.","small");
    s+=endSVG(); return s;
}
int main(){ string dir="output/12_polynomial_chain_steps"; ensureDir(dir); for(int i=1;i<=8;i++){ char buf[256]; sprintf(buf,"%s/step_%02d.svg",dir.c_str(),i); writeFile(buf,drawFrame(i)); } cout<<"Generated 8 SVG frames: "<<dir<<"\n"; return 0;}
